name: pip_services3_commons
version: "1.0.3"
author: Sergey Seroukhov <seroukhov@gmail.com>
description: Common patterns for Pip.Services in Dart. This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project.
homepage: https://github.com/pip-services3-dart/pip-services3-commons-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  uuid: ">=2.0.4 < 3.0.0"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'